/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
// WARNING
// This file has been autogenerated.
// Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef M4DEVICEREADER_PROXY_H
#define M4DEVICEREADER_PROXY_H

#include <ComponentAPI.h>
#include <ApplicationListenerAPI.h>
#include <ComponentReloadingListenerAPI.h>
#include <HaptechDeviceAPI.h>
#include <MissionListenerAPI.h>
#include <WeaponSystemAspectListenerAPI.h>

GEARS_EXPORT void GEARS_API RegisterAPI_v6(APIManager_RegisterAPI_Func_v6 register_api);

#endif
