/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
// WARNING
// This file has been autogenerated.
// Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef M4DEVICEREADER_MOCK_H
#define M4DEVICEREADER_MOCK_H

#include <ComponentAPI.h>
#include <ApplicationListenerAPI.h>
#include <ComponentReloadingListenerAPI.h>
#include <HaptechDeviceAPI.h>
#include <MissionListenerAPI.h>
#include <WeaponSystemAspectListenerAPI.h>


#endif
