/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
// WARNING
// This file has been autogenerated.
// Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#include "M4DeviceReaderProxy.h"
#include "M4DeviceReader.h"
#include <GUIAPI.h>

GEARS_EXPORT void GEARS_API RegisterAPI_v6(APIManager_RegisterAPI_Func_v6 register_api)
{
  // Register ComponentAPI_v6
  {
    static ComponentAPI_v6 api;
    APIInfo_v6 api_info;

    api.Initialize = Component_Initialize;
    api.OnStart = Component_OnStart;
    api.OnStop = Component_OnStop;
    api.Shutdown = Component_Shutdown;
    api.IsParallelizable = Component_IsParallelizable;
    api.GetName = Component_GetName;
    api.GetVersion = Component_GetVersion;

    api_info._api = &api;
    api_info._version = 6;
    api_info._privilege = 0;

    register_api(ComponentAPI_Handle, &api_info);
  }

  // Register ApplicationListenerAPI_v2
  {
    static ApplicationListenerAPI_v2 api;
    APIInfo_v6 api_info;

    api.OnApplicationReady = ApplicationListener_OnApplicationReady;
    api.OnBeforeUpdate = ApplicationListener_OnBeforeUpdate;
    api.OnAfterUpdate = ApplicationListener_OnAfterUpdate;

    api_info._api = &api;
    api_info._version = 2;
    api_info._privilege = 0;

    register_api(ApplicationListenerAPI_Handle, &api_info);
  }

#ifdef DEBUG
  // Register ComponentReloadingListenerAPI_v1
  {
    static ComponentReloadingListenerAPI_v1 api;
    APIInfo_v6 api_info;

    api.BeforeUnload = ComponentReloadingListener_BeforeUnload;
    api.AfterReload = ComponentReloadingListener_AfterReload;

    api_info._api = &api;
    api_info._version = 1;
    api_info._privilege = 0;

    register_api(ComponentReloadingListenerAPI_Handle, &api_info);
  }
#endif

  // Register HaptechDeviceAPI_v2
  {
    static HaptechDeviceAPI_v2 api;
    APIInfo_v6 api_info;

    api.GetDeviceState = HaptechDevice_GetDeviceState;
    api.test = HaptechDevice_test;
    api.ParseDeviceUpdates = HaptechDevice_ParseDeviceUpdates;

    api_info._api = &api;
    api_info._version = 2;
    api_info._privilege = 0;

    register_api(HaptechDeviceAPI_Handle, &api_info);
  }
}
