/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
// WARNING
// This file has been autogenerated.
// Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef M4DEVICEREADER_RELOADING_MODULE_H
#define M4DEVICEREADER_RELOADING_MODULE_H

#include <ComponentAPI.h>
#include <ApplicationListenerAPI.h>
#include <ComponentReloadingListenerAPI.h>
#include <HaptechDeviceAPI.h>

GEARS_EXPORT void GEARS_API RegisterAPI_v6(APIManager_RegisterAPI_Func_v6 register_api);

GEARS_EXPORT APIResult GEARS_API Wrapper_Component_LoadComponent(_In_ HMODULE component_dll);
APIResult GEARS_API Wrapper_Component_Initialize(_In_ const char* component_folder);
APIResult GEARS_API Wrapper_Component_OnStart(_In_ APIManager_v6* api_manager, _In_ NativeModuleHandle proxy_handle);
APIResult GEARS_API Wrapper_Component_OnStop();
APIResult GEARS_API Wrapper_Component_Shutdown();
APIResult GEARS_API Wrapper_Component_IsParallelizable(_Out_ bool32_t* parallelizable);
APIResult GEARS_API Wrapper_Component_GetName(_Inout_ int32_t* name_length, _Out_opt_ char* name);
APIResult GEARS_API Wrapper_Component_GetVersion(_Inout_ int32_t* version_length, _Out_opt_ char* version);

void GEARS_API Wrapper_ApplicationListener_OnApplicationReady();
void GEARS_API Wrapper_ApplicationListener_OnBeforeUpdate(_In_ float32_t application_delta_time, _In_ float32_t simulation_delta_time);
void GEARS_API Wrapper_ApplicationListener_OnAfterUpdate(_In_ float32_t application_delta_time, _In_ float32_t simulation_delta_time);

APIResult GEARS_API Wrapper_ComponentReloadingListener_BeforeUnload();
APIResult GEARS_API Wrapper_ComponentReloadingListener_AfterReload(_In_ const char* component_folder);

APIResult GEARS_API Wrapper_HaptechDevice_GetDeviceState(_In_ const char* device_hex_address, _In_ const char* device_sensor, _Out_ int8_t* sensor_state);
APIResult GEARS_API Wrapper_HaptechDevice_test(_In_ const char* test_string, _In_ int32_t test_int);
APIResult GEARS_API Wrapper_HaptechDevice_ParseDeviceUpdates();

#endif
