/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
// WARNING
// This file has been autogenerated.
// Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#include "M4DeviceReaderReloadingModule.h"
#include "M4DeviceReaderUnloadedPlaceholders.h"
#include <GUIAPI.h>

HMODULE g_component_dll = nullptr;
APIResult g_load_result = kAPIResult_GeneralSuccess;
__declspec(align(32)) volatile uint32_t g_active_function_count = 0;

struct ImplementedAPIs
{
  ComponentAPI_v6 _component_v6;
  ApplicationListenerAPI_v2 _application_listener_v2;
  ComponentReloadingListenerAPI_v1 _component_reloading_listener_v1;
  HaptechDeviceAPI_v2 _haptech_device_v2;
};

ImplementedAPIs g_current_apis;
ImplementedAPIs g_implementation_apis;
ImplementedAPIs g_unloaded_apis;

GEARS_EXPORT void GEARS_API RegisterAPI_v6(APIManager_RegisterAPI_Func_v6 register_api)
{
  // Clear out the function pointers
  memset(&g_current_apis, 0, sizeof(g_current_apis));
  memset(&g_implementation_apis, 0, sizeof(g_implementation_apis));
  memset(&g_unloaded_apis, 0, sizeof(g_unloaded_apis));

  // Set up unloaded placeholder function pointers
  g_unloaded_apis._component_v6.Initialize = Unloaded_Component_Initialize;
  g_unloaded_apis._component_v6.OnStart = Unloaded_Component_OnStart;
  g_unloaded_apis._component_v6.OnStop = Unloaded_Component_OnStop;
  g_unloaded_apis._component_v6.Shutdown = Unloaded_Component_Shutdown;
  g_unloaded_apis._component_v6.IsParallelizable = Unloaded_Component_IsParallelizable;
  g_unloaded_apis._component_v6.GetName = Unloaded_Component_GetName;
  g_unloaded_apis._component_v6.GetVersion = Unloaded_Component_GetVersion;
  g_unloaded_apis._application_listener_v2.OnApplicationReady = Unloaded_ApplicationListener_OnApplicationReady;
  g_unloaded_apis._application_listener_v2.OnBeforeUpdate = Unloaded_ApplicationListener_OnBeforeUpdate;
  g_unloaded_apis._application_listener_v2.OnAfterUpdate = Unloaded_ApplicationListener_OnAfterUpdate;
  g_unloaded_apis._component_reloading_listener_v1.BeforeUnload = Unloaded_ComponentReloadingListener_BeforeUnload;
  g_unloaded_apis._component_reloading_listener_v1.AfterReload = Unloaded_ComponentReloadingListener_AfterReload;
  g_unloaded_apis._haptech_device_v2.GetDeviceState = Unloaded_HaptechDevice_GetDeviceState;
  g_unloaded_apis._haptech_device_v2.test = Unloaded_HaptechDevice_test;
  g_unloaded_apis._haptech_device_v2.ParseDeviceUpdates = Unloaded_HaptechDevice_ParseDeviceUpdates;

  // Point current functions to unloaded placeholders
  g_current_apis._component_v6 = g_unloaded_apis._component_v6;
  g_current_apis._application_listener_v2 = g_unloaded_apis._application_listener_v2;
  g_current_apis._component_reloading_listener_v1 = g_unloaded_apis._component_reloading_listener_v1;
  g_current_apis._haptech_device_v2 = g_unloaded_apis._haptech_device_v2;

  // Register ComponentAPI_v6
  {
    static ComponentAPI_v6 api;
    APIInfo_v6 api_info;

    api.Initialize = Wrapper_Component_Initialize;
    api.OnStart = Wrapper_Component_OnStart;
    api.OnStop = Wrapper_Component_OnStop;
    api.Shutdown = Wrapper_Component_Shutdown;
    api.IsParallelizable = Wrapper_Component_IsParallelizable;
    api.GetName = Wrapper_Component_GetName;
    api.GetVersion = Wrapper_Component_GetVersion;

    api_info._api = &api;
    api_info._version = 6;
    api_info._privilege = 0;

    register_api(ComponentAPI_Handle, &api_info);
  }

  // Register ApplicationListenerAPI_v2
  {
    static ApplicationListenerAPI_v2 api;
    APIInfo_v6 api_info;

    api.OnApplicationReady = Wrapper_ApplicationListener_OnApplicationReady;
    api.OnBeforeUpdate = Wrapper_ApplicationListener_OnBeforeUpdate;
    api.OnAfterUpdate = Wrapper_ApplicationListener_OnAfterUpdate;

    api_info._api = &api;
    api_info._version = 2;
    api_info._privilege = 0;

    register_api(ApplicationListenerAPI_Handle, &api_info);
  }

  // Register ComponentReloadingListenerAPI_v1
  {
    static ComponentReloadingListenerAPI_v1 api;
    APIInfo_v6 api_info;

    api.BeforeUnload = Wrapper_ComponentReloadingListener_BeforeUnload;
    api.AfterReload = Wrapper_ComponentReloadingListener_AfterReload;

    api_info._api = &api;
    api_info._version = 1;
    api_info._privilege = 0;

    register_api(ComponentReloadingListenerAPI_Handle, &api_info);
  }

  // Register HaptechDeviceAPI_v2
  {
    static HaptechDeviceAPI_v2 api;
    APIInfo_v6 api_info;

    api.GetDeviceState = Wrapper_HaptechDevice_GetDeviceState;
    api.test = Wrapper_HaptechDevice_test;
    api.ParseDeviceUpdates = Wrapper_HaptechDevice_ParseDeviceUpdates;

    api_info._api = &api;
    api_info._version = 2;
    api_info._privilege = 0;

    register_api(HaptechDeviceAPI_Handle, &api_info);
  }
}

void RegisterComponentAPI(const char* api_name, const APIInfo_v6* api_info)
{
  if(strcmp(api_name, ComponentAPI_Handle) == 0 && api_info->_version == 6)
  {
    g_implementation_apis._component_v6 = *reinterpret_cast<ComponentAPI_v6*>(api_info->_api);
  }
  else if(strcmp(api_name, ApplicationListenerAPI_Handle) == 0 && api_info->_version == 2)
  {
    g_implementation_apis._application_listener_v2 = *reinterpret_cast<ApplicationListenerAPI_v2*>(api_info->_api);
  }
  else if(strcmp(api_name, ComponentReloadingListenerAPI_Handle) == 0 && api_info->_version == 1)
  {
    g_implementation_apis._component_reloading_listener_v1 = *reinterpret_cast<ComponentReloadingListenerAPI_v1*>(api_info->_api);
  }
  else if(strcmp(api_name, HaptechDeviceAPI_Handle) == 0 && api_info->_version == 2)
  {
    g_implementation_apis._haptech_device_v2 = *reinterpret_cast<HaptechDeviceAPI_v2*>(api_info->_api);
  }
  else
  {
    g_load_result = kAPIResult_ReloadError_UnexpectedAPI;
  }
}

GEARS_EXPORT APIResult GEARS_API Wrapper_Component_LoadComponent(_In_ HMODULE component_dll)
{
  // Clear implementation pointers
  memset(&g_implementation_apis, 0, sizeof(g_implementation_apis));

  // Check if its already loaded
  if(g_component_dll != nullptr)
  {
    return kAPIResult_GeneralError;
  }

  g_load_result = kAPIResult_GeneralSuccess;
  g_component_dll = component_dll;

  if(g_component_dll != nullptr)
  {
    // Get the register function
    typedef void (GEARS_API *RegisterFunc)(APIManager_RegisterAPI_Func_v6);
    RegisterFunc register_func = (RegisterFunc)GetProcAddress(g_component_dll, "RegisterAPI_v6");
    if(register_func != nullptr)
    {
      register_func(RegisterComponentAPI);
    }
    else
    {
      g_load_result = kAPIResult_ReloadError_MissingFunction;
    }

    if(APIRESULT_SUCCESS(g_load_result) == false)
    {
      // Clear implementation pointers
      memset(&g_implementation_apis, 0, sizeof(g_implementation_apis));

      // Unload dll
      FreeLibrary(g_component_dll);
      g_component_dll = nullptr;
    }
  }
  else
  {
    g_load_result = kAPIResult_ReloadError_DLLFailedToLoad;
  }

  return g_load_result;
}

APIResult GEARS_API Wrapper_Component_Initialize(_In_ const char* component_folder)
{
  APIResult return_value;
  if(g_implementation_apis._component_v6.Initialize != nullptr)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_implementation_apis._component_v6.Initialize(component_folder);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_v6.Initialize(component_folder);
  }

  // Point current functions to implementation
  g_current_apis._component_v6 = g_implementation_apis._component_v6;
  g_current_apis._application_listener_v2 = g_implementation_apis._application_listener_v2;
  g_current_apis._component_reloading_listener_v1 = g_implementation_apis._component_reloading_listener_v1;
  g_current_apis._haptech_device_v2 = g_implementation_apis._haptech_device_v2;
  return return_value;
}

APIResult GEARS_API Wrapper_Component_OnStart(_In_ APIManager_v6* api_manager, _In_ NativeModuleHandle proxy_handle)
{
  APIResult return_value;
  if(g_current_apis._component_v6.OnStart == g_implementation_apis._component_v6.OnStart)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._component_v6.OnStart(api_manager, proxy_handle);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_v6.OnStart(api_manager, proxy_handle);
  }
  return return_value;
}

APIResult GEARS_API Wrapper_Component_OnStop()
{
  APIResult return_value;
  if(g_current_apis._component_v6.OnStop == g_implementation_apis._component_v6.OnStop)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._component_v6.OnStop();
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_v6.OnStop();
  }
  return return_value;
}

APIResult GEARS_API Wrapper_Component_Shutdown()
{
  // Point current functions to unloaded placeholders
  g_current_apis._component_v6 = g_unloaded_apis._component_v6;
  g_current_apis._application_listener_v2 = g_unloaded_apis._application_listener_v2;
  g_current_apis._component_reloading_listener_v1 = g_unloaded_apis._component_reloading_listener_v1;
  g_current_apis._haptech_device_v2 = g_unloaded_apis._haptech_device_v2;

  // Wait for any current API calls to finish
  while(InterlockedCompareExchange(&g_active_function_count, 0, 0) != 0)
  {
  }

  APIResult return_value;
  if(g_implementation_apis._component_v6.Shutdown != nullptr)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_implementation_apis._component_v6.Shutdown();
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_v6.Shutdown();
  }

  // Clear implementation pointers
  memset(&g_implementation_apis, 0, sizeof(g_implementation_apis));

  // Unload dll
  FreeLibrary(g_component_dll);
  g_component_dll = nullptr;

  return return_value;
}

APIResult GEARS_API Wrapper_Component_IsParallelizable(_Out_ bool32_t* parallelizable)
{
  APIResult return_value;
  if(g_current_apis._component_v6.IsParallelizable == g_implementation_apis._component_v6.IsParallelizable)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._component_v6.IsParallelizable(parallelizable);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_v6.IsParallelizable(parallelizable);
  }
  return return_value;
}

APIResult GEARS_API Wrapper_Component_GetName(_Inout_ int32_t* name_length, _Out_opt_ char* name)
{
  APIResult return_value;
  if(g_current_apis._component_v6.GetName == g_implementation_apis._component_v6.GetName)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._component_v6.GetName(name_length, name);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_v6.GetName(name_length, name);
  }
  return return_value;
}

APIResult GEARS_API Wrapper_Component_GetVersion(_Inout_ int32_t* version_length, _Out_opt_ char* version)
{
  APIResult return_value;
  if(g_current_apis._component_v6.GetVersion == g_implementation_apis._component_v6.GetVersion)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._component_v6.GetVersion(version_length, version);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_v6.GetVersion(version_length, version);
  }
  return return_value;
}

void GEARS_API Wrapper_ApplicationListener_OnApplicationReady()
{
  if(g_current_apis._application_listener_v2.OnApplicationReady == g_implementation_apis._application_listener_v2.OnApplicationReady)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    g_current_apis._application_listener_v2.OnApplicationReady();
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    g_unloaded_apis._application_listener_v2.OnApplicationReady();
  }
}

void GEARS_API Wrapper_ApplicationListener_OnBeforeUpdate(_In_ float32_t application_delta_time, _In_ float32_t simulation_delta_time)
{
  if(g_current_apis._application_listener_v2.OnBeforeUpdate == g_implementation_apis._application_listener_v2.OnBeforeUpdate)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    g_current_apis._application_listener_v2.OnBeforeUpdate(application_delta_time, simulation_delta_time);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    g_unloaded_apis._application_listener_v2.OnBeforeUpdate(application_delta_time, simulation_delta_time);
  }
}

void GEARS_API Wrapper_ApplicationListener_OnAfterUpdate(_In_ float32_t application_delta_time, _In_ float32_t simulation_delta_time)
{
  if(g_current_apis._application_listener_v2.OnAfterUpdate == g_implementation_apis._application_listener_v2.OnAfterUpdate)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    g_current_apis._application_listener_v2.OnAfterUpdate(application_delta_time, simulation_delta_time);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    g_unloaded_apis._application_listener_v2.OnAfterUpdate(application_delta_time, simulation_delta_time);
  }
}

APIResult GEARS_API Wrapper_ComponentReloadingListener_BeforeUnload()
{
  APIResult return_value;
  if(g_current_apis._component_reloading_listener_v1.BeforeUnload == g_implementation_apis._component_reloading_listener_v1.BeforeUnload)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._component_reloading_listener_v1.BeforeUnload();
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_reloading_listener_v1.BeforeUnload();
  }
  return return_value;
}

APIResult GEARS_API Wrapper_ComponentReloadingListener_AfterReload(_In_ const char* component_folder)
{
  APIResult return_value;
  if(g_current_apis._component_reloading_listener_v1.AfterReload == g_implementation_apis._component_reloading_listener_v1.AfterReload)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._component_reloading_listener_v1.AfterReload(component_folder);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._component_reloading_listener_v1.AfterReload(component_folder);
  }
  return return_value;
}

APIResult GEARS_API Wrapper_HaptechDevice_GetDeviceState(_In_ const char* device_hex_address, _In_ const char* device_sensor, _Out_ int8_t* sensor_state)
{
  APIResult return_value;
  if(g_current_apis._haptech_device_v2.GetDeviceState == g_implementation_apis._haptech_device_v2.GetDeviceState)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._haptech_device_v2.GetDeviceState(device_hex_address, device_sensor, sensor_state);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._haptech_device_v2.GetDeviceState(device_hex_address, device_sensor, sensor_state);
  }
  return return_value;
}

APIResult GEARS_API Wrapper_HaptechDevice_test(_In_ const char* test_string, _In_ int32_t test_int)
{
  APIResult return_value;
  if(g_current_apis._haptech_device_v2.test == g_implementation_apis._haptech_device_v2.test)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._haptech_device_v2.test(test_string, test_int);
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._haptech_device_v2.test(test_string, test_int);
  }
  return return_value;
}

APIResult GEARS_API Wrapper_HaptechDevice_ParseDeviceUpdates()
{
  APIResult return_value;
  if(g_current_apis._haptech_device_v2.ParseDeviceUpdates == g_implementation_apis._haptech_device_v2.ParseDeviceUpdates)
  {
    // Forward to implementation
    InterlockedIncrement(&g_active_function_count);
    return_value = g_current_apis._haptech_device_v2.ParseDeviceUpdates();
    InterlockedDecrement(&g_active_function_count);
  }
  else
  {
    // Forward to unloaded placeholder
    return_value = g_unloaded_apis._haptech_device_v2.ParseDeviceUpdates();
  }
  return return_value;
}
