/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////
//WARNING
//This file has been autogenerated.
//Do NOT make modifications directly to it as they will be overwritten!
/////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////

#ifndef HAPTECHDEVICE_API_H
#define HAPTECHDEVICE_API_H

#include <CoreAPI.h>

/**
 API Version:       HaptechDevice API v1

 New Functions:
 GetM4DeviceUsingStringAddress -
 */

/**
  @brief GetM4DeviceUsingStringAddress v1

  @param device
         parameter description

  @return APIResult
          return description
  */

typedef APIResult (GEARS_API *HaptechDevice_GetM4DeviceUsingStringAddress_Func_v1)(_Out_ void* device);

typedef struct HaptechDeviceAPI_v1
{
  HaptechDevice_GetM4DeviceUsingStringAddress_Func_v1   GetM4DeviceUsingStringAddress;
} HaptechDeviceAPI_v1;

static const char* HaptechDeviceAPI_SHA_v1 = "7ddd9aa1015d2936a8ebf64cac07b389c081881f";

static const char* HaptechDeviceAPI_Handle = "HaptechDeviceAPI";

#endif
